export interface IlaunchesX {
    "flight_number": number,
    "mission_name": string,
    "mission_id": [],
    "launch_year": string,
    "launch_date_unix": number,
    "launch_date_utc": string,
    "launch_date_local": string,
    "is_tentative": false,
    "tentative_max_precision": string,
    "tbd": boolean,
    "launch_window": number,
    "rocket": object,
    "ships": [],
    "telemetry": object,
    "launch_site": object,
    "launch_success": boolean,
    "links": object,
    "details": string,
    "upcoming": boolean,
    "static_fire_date_utc": string,
    "static_fire_date_unix": number,
    "timeline": object,
    "crew": object
}